version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
