version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:80
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
