import { useQuery } from "@apollo/client";
import { accountsQuery } from "../graphql/queries/AccountsQuery";
import { AccountsResponse } from "../types";
import { useMemo } from "react";

const rows = [
  {
    id: "1",
    name: "John Doe",
    type: "Farmer",
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "2",
    name: "Jane Doe",
    type: "Buyer",
    firstName: "Jane",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "3",
    name: "John Doe",
    type: "Agent",
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "4",
    name: "Jane Doe",
    type: "Plot",
    firstName: "Jane",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "5",
    name: "John Doe",
    type: "Farmer",
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "6",
    name: "Jane Doe",
    type: "Farmer",
    firstName: "Jane",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "7",
    name: "John Doe",
    type: "Farmer",
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "8",
    name: "Jane Doe",
    type: "Farmer",
    firstName: "Jane",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
    completeness: 100,
  },
  {
    id: "9",
    name: "John Doe",
    type: "Farmer",
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Inactive",
    completeness: 100,
  },
  {
    id: "10",
    name: "Jane Doe",
    type: "Farmer",
    firstName: "Jane",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    completeness: 100,
  },
  {
    id: "11",
    name: "John Doe",
    type: "Farmer",
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
    completeness: 100,
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Active",
  },
  {
    id: "12",
    name: "Jane Doe",
    type: "Farmer",
    firstName: "Jane",
    completeness: 100,
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
    status: "Inactive",
  },
  {
    id: "13",
    name: "John Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
    district: "Nairobi",
  },
  {
    id: "14",
    name: "Jane Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "Jane",
    lastName: "Doe",
    govId: "123456789",
    mobileNumber: "123456789",
  },
  {
    id: "15",
    name: "John Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "John",
    lastName: "Doe",
    govId: "123456789",
  },
  {
    id: "16",
    name: "Jane Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "Jane",
    lastName: "Doe",
  },
  {
    id: "17",
    name: "John Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "John",
  },
  {
    id: "18",
    name: "Jane Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "Jane",
  },
  {
    id: "19",
    name: "John Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "John",
  },
  {
    id: "20",
    name: "Jane Doe",
    type: "Farmer",
    completeness: 100,
    firstName: "Jane",
  },
];

const loading = false
export const useAccountsTableRows = () => {
  /* const { data, loading } = useQuery<AccountsResponse>(accountsQuery);
  const rows = useMemo(
    () =>
      data?.accounts.data.map((account) => ({
        id: account.id,
        name: account.attributes.name,
        type: account.attributes.type,
        firstName: account.attributes.firstName,
        lastName: account.attributes.lastName,
        govId: account.attributes.govId,
        mobileNumber: account.attributes.mobileNumber,
        district: account.attributes.district,
        status: account.attributes.status,
        completeness: account.attributes.completeness,
      })) || [],
    [data]
  ); */
  
  return { rows, loading };
};
