export const useReceiptionsTableRows = () => {
  return [
    {
      id: 1,
      receptionDate: "2022-01-1",
      status: "Pending",
      accountId: "1001",
      accountName: "Account 1",
      lotNumber: "Lot 1",
      grade: "B",
      weight: 10,
      totalCost: 100,
      payment: "Paid",
    },
    {
      id: 2,
      receptionDate: "2022-01-2",
      status: "Received",
      accountId: "1002",
      accountName: "Account 2",
      lotNumber: "Lot 2",
      grade: "B",
      weight: 20,
      totalCost: 200,
      payment: "Paid",
    },
    {
      id: 3,
      receptionDate: "2022-01-3",
      status: "Pending",
      accountId: "1003",
      accountName: "Account 3",
      lotNumber: "Lot 3",
      grade: "A",
      weight: 30,
      totalCost: 300,
      payment: "Paid",
    },
    {
      id: 4,
      receptionDate: "2022-01-4",
      status: "Received",
      accountId: "1004",
      accountName: "Account 4",
      lotNumber: "Lot 4",
      grade: "B",
      weight: 40,
      totalCost: 400,
      payment: "Due",
    },
    {
      id: 5,
      receptionDate: "2022-01-5",
      status: "Pending",
      accountId: "1005",
      accountName: "Account 5",
      lotNumber: "Lot 5",
      grade: "B",
      weight: 50,
      totalCost: 500,
      payment: "Paid",
    },
    {
      id: 6,
      receptionDate: "2022-01-6",
      status: "Received",
      accountId: "1006",
      accountName: "Account 6",
      lotNumber: "Lot 6",
      grade: "A",
      weight: 60,
      totalCost: 600,
      payment: "Paid",
    },
    {
      id: 7,
      receptionDate: "2022-01-7",
      status: "Pending",
      accountId: "1007",
      accountName: "Account 7",
      lotNumber: "Lot 7",
      grade: "B",
      weight: 70,
      totalCost: 700,
      payment: "Paid",
    },
    {
      id: 8,
      receptionDate: "2022-01-8",
      status: "Received",
      accountId: "1008",
      accountName: "Account 8",
      lotNumber: "Lot 8",
      grade: "B",
      weight: 80,
      totalCost: 800,
      payment: "Due",
    },
    {
      id: 9,
      receptionDate: "2022-01-9",
      status: "Pending",
      accountId: "1009",
      accountName: "Account 9",
      lotNumber: "Lot 9",
      grade: "A",
      weight: 90,
      totalCost: 900,
      payment: "Paid",
    },
    {
      id: 10,
      receptionDate: "2022-01-10",
      status: "Received",
      accountId: "10010",
      accountName: "Account 10",
      lotNumber: "Lot 10",
      grade: "B",
      weight: 100,
      totalCost: 1000,
      payment: "Paid",
    },
    {
      id: 11,
      receptionDate: "2022-01-11",
      status: "Pending",
      accountId: "10011",
      accountName: "Account 11",
      lotNumber: "Lot 11",
      grade: "B",
      weight: 110,
      totalCost: 1100,
      payment: "Paid",
    },
    {
      id: 12,
      receptionDate: "2022-01-12",
      status: "Received",
      accountId: "10012",
      accountName: "Account 12",
      lotNumber: "Lot 12",
      grade: "A",
      weight: 120,
      totalCost: 1200,
      payment: "Due",
    },
    {
      id: 13,
      receptionDate: "2022-01-13",
      status: "Pending",
      accountId: "10013",
      accountName: "Account 13",
      lotNumber: "Lot 13",
      grade: "B",
      weight: 130,
      totalCost: 1300,
      payment: "Paid",
    },
    {
      id: 14,
      receptionDate: "2022-01-14",
      status: "Received",
      accountId: "10014",
      accountName: "Account 14",
      lotNumber: "Lot 14",
      grade: "B",
      weight: 140,
      totalCost: 1400,
      payment: "Paid",
    },
    {
      id: 15,
      receptionDate: "2022-01-15",
      status: "Pending",
      accountId: "10015",
      accountName: "Account 15",
      lotNumber: "Lot 15",
      grade: "A",
      weight: 150,
      totalCost: 1500,
      payment: "Paid",
    },
    {
      id: 16,
      receptionDate: "2022-01-16",
      status: "Received",
      accountId: "10016",
      accountName: "Account 16",
      lotNumber: "Lot 16",
      grade: "B",
      weight: 160,
      totalCost: 1600,
      payment: "Due",
    },
    {
      id: 17,
      receptionDate: "2022-01-17",
      status: "Pending",
      accountId: "10017",
      accountName: "Account 17",
      lotNumber: "Lot 17",
      grade: "B",
      weight: 170,
      totalCost: 1700,
      payment: "Paid",
    },
    {
      id: 18,
      receptionDate: "2022-01-18",
      status: "Received",
      accountId: "10018",
      accountName: "Account 18",
      lotNumber: "Lot 18",
      grade: "A",
      weight: 180,
      totalCost: 1800,
      payment: "Paid",
    },
    {
      id: 19,
      receptionDate: "2022-01-19",
      status: "Pending",
      accountId: "10019",
      accountName: "Account 19",
      lotNumber: "Lot 19",
      grade: "B",
      weight: 190,
      totalCost: 1900,
      payment: "Paid",
    },
    {
      id: 20,
      receptionDate: "2022-01-20",
      status: "Received",
      accountId: "10020",
      accountName: "Account 20",
      lotNumber: "Lot 20",
      grade: "B",
      weight: 200,
      totalCost: 2000,
      payment: "Due",
    },
  ];
};
